image: gitpod/workspace-dotnet:2024-05-08-19-39-59
# tool-dotnet config:           https://github.com/gitpod-io/workspace-images/tree/main/chunks/tool-dotnet
# gitpod/workspace-dotnet tags: https://hub.docker.com/r/gitpod/workspace-dotnet/tags


tasks:
  - name: Restore & Build
    init: |
      dotnet dev-certs https 
      dotnet restore
      dotnet build
vscode:
  extensions:
    - muhammad-sammy.csharp
